Expanding the doctor's profile and adding a rating
MathAndMedLab/Medical-Web-App pull request #63
Opened 2022-12-04 14:46 UTC by lastdesire

Next features done:
• Fixed some design troubles in newHome page + added links to pages
• Added an icon for the tab
• Inserted the display of the online user (here we need a script that will check the user's activity on the site: if it is not there for a long time, then put it offline)
• Made user rating and reviews counter on profile page
• Expanded search page with avatars, online, reviews counter and rating
• Supplemented doctor's profile with next rows: education, workplace, work experience, specialization
• Created the ability to edit profile
• Wrote tests for the backend

2022-12-04 18:57 UTC, yurii-litvinov requested changes
favicon(1).ico точно нужна? :)

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/avg_rating/get_avg_rating.js
> +function GetAvgRating(rvws, len) {
По-хорошему надо комментарии ещё

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/main/newHome.component.js
> +    secondTittle: {
Title. Иначе это как-то неприлично звучит :)

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/main/newHome.component.js
> +                        <a href="http://localhost:3000/local"> Получите отчет от искусственного интеллекта </a>
О, ссылка на localhost. Думаю что не будет работать, если приложение выложить хоть куда-нибудь :)

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/search/search.component.js
> +    //
:(

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/signin_signup/login.component.js
> +
Две пустые строки подряд обычно нигде не ставят

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/signin_signup/register.component.js
> +        if (chosenRole === "Пользователь") {
Стоило бы вынести роли в константы хотя бы, а то где-нибудь опечатались в названии роли --- беда

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/signin_signup/register.component.js
> +                            //onClick={handleRegister}
Закомментированный код не нужен

2022-12-04 18:57 UTC, yurii-litvinov commented on med-web-app-front/src/components/user_profile/profile-edit.component.js
> +    return (
```suggestion
    }

    return (
```

2022-12-04 18:57 UTC, yurii-litvinov commented on src/test/java/com/app/medicalwebapp/services/AuthServiceTest.java
> +//import com.app.medicalwebapp.controllers.AuthController;
:(

2022-12-04 18:57 UTC, yurii-litvinov commented on src/test/java/com/app/medicalwebapp/services/AuthServiceTest.java
> +        if (!userRepository.existsByUsername("user")) {
А если exists?

2022-12-06 18:48 UTC, lastdesire commented on med-web-app-front/src/avg_rating/get_avg_rating.js
> +function GetAvgRating(rvws, len) {
Сделал.

2022-12-06 18:48 UTC, lastdesire commented on med-web-app-front/src/components/main/newHome.component.js
> +    secondTittle: {
Поправил.

2022-12-06 18:50 UTC, lastdesire commented on med-web-app-front/src/components/search/search.component.js
> +    //
Теперь :)

2022-12-06 18:51 UTC, lastdesire commented on med-web-app-front/src/components/signin_signup/login.component.js
> +
Справедливо, убрал.

2022-12-06 18:56 UTC, lastdesire commented on med-web-app-front/src/components/signin_signup/register.component.js
> +        if (chosenRole === "Пользователь") {
Согласен, это тоже поправил.

2022-12-06 18:59 UTC, lastdesire commented on med-web-app-front/src/components/signin_signup/register.component.js
> +                            //onClick={handleRegister}
А не плохо ли удалять не свои комментарии?

2022-12-06 19:11 UTC, lastdesire commented on src/test/java/com/app/medicalwebapp/services/AuthServiceTest.java
> +//import com.app.medicalwebapp.controllers.AuthController;
Убрал.

2022-12-06 19:12 UTC, lastdesire commented on src/test/java/com/app/medicalwebapp/services/AuthServiceTest.java
> +        if (!userRepository.existsByUsername("user")) {
Лишняя проверка, полагаю.

2022-12-21 17:51 UTC, merged